# Generated by Django 5.2.5 on 2025-08-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
